# Generated by Django 2.0.5 on 2018-08-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
